#ifndef INPUTMAP_H
#define INPUTMAP_H

#define INPUT_UP SDLK_UP
#define INPUT_DOWN SDLK_DOWN
#define INPUT_LEFT SDLK_LEFT
#define INPUT_RIGHT SDLK_RIGHT
#define INPUT_LMOD SDLK_LCTRL
#define INPUT_RMOD SDLK_RCTRL
#define INPUT_PGDOWN SDLK_PAGEDOWN
#define INPUT_PGUP SDLK_PAGEUP
#define INPUT_ZOOMIN SDLK_KP_PLUS
#define INPUT_ZOOMOUT SDLK_KP_MINUS
#define INPUT_PAGEN SDLK_g
#define INPUT_CLEAR SDLK_c
#define INPUT_CANCEL SDLK_BACKSPACE
#define INPUT_CONFIRM SDLK_RETURN
#define INPUT_EXIT SDLK_ESCAPE
#define INPUT_QUIT SDLK_q
#define INPUT_HELP SDLK_F1

#define STR_UP "UP"
#define STR_DOWN "DOWN"
#define STR_LEFT "LEFT"
#define STR_RIGHT "RIGHT"
#define STR_LMOD "LCTRL"
#define STR_RMOD "RCTRL"
#define STR_PGDOWN "PAGE_DOWN"
#define STR_PGUP "PAGE_UP"
#define STR_ZOOMIN "NUM+"
#define STR_ZOOMOUT "NUM-"
#define STR_PAGEN "G"
#define STR_CLEAR "C"
#define STR_CANCEL "BACKSPACE"
#define STR_CONFIRM "RETURN"
#define STR_EXIT "ESC"
#define STR_QUIT "Q"
#define STR_HELP "F1"

#endif
