#Makefile autogenerated by RcB2
prefix = /usr/local
bindir = $(prefix)/bin

PROG = sdlbook
SRCS = sdlbook.c
OBJS = $(SRCS:.c=.o)

-include config.mak

ifeq ($(SDL2),)
SDL_LIBS = -lSDL
CPPF_SDL =
else
SDL_LIBS = -lSDL2
CPPF_SDL = -DUSE_SDL2
endif

LIBS = -ldjvulibre -lmupdf $(SDL_LIBS) -lm

CFLAGS_N = 
CPPFLAGS_N = $(CPPF_SDL)
LDFLAGS_N = 

MAKEFILE := $(firstword $(MAKEFILE_LIST))

all: $(PROG)

clean:
	rm -f $(PROG)
	rm -f $(OBJS)

rebuild:
	$(MAKE) -f $(MAKEFILE) clean && $(MAKE) -f $(MAKEFILE) all

install: $(PROG)
	install -d $(DESTDIR)/$(bindir)
	install -D -m 755 $(PROG) $(DESTDIR)/$(bindir)/

src: $(SRCS)
	$(CC) $(CPPFLAGS_N) $(CPPFLAGS) $(CFLAGS_N) $(CFLAGS) -o $(PROG) $^ $(LDFLAGS_N) $(LDFLAGS) $(LIBS)

sdlbook.o: ezsdl.h

%.o: %.c
	$(CC) $(CPPFLAGS_N) $(CPPFLAGS) $(CFLAGS_N) $(CFLAGS) -c -o $@ $<

$(PROG): $(OBJS)
	$(CC) $(CFLAGS_N) $(CFLAGS) $(LDFLAGS_N) $(LDFLAGS) $(OBJS) $(LIBS) -o $@

.PHONY: all clean rebuild install src
